name: Azure Web App CI/CD

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      # Optional: If you're using custom build steps, specify them here
      - name: Setup Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: "austin-stewart"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
